version: '3.8'

services:
  event-gateway:
    build: .
    container_name: event-gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGODB_URI=mongodb://mongodb:27017/streaming
      - SERVER_PORT=8080
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
      - event-gateway
    entrypoint: >
      /bin/sh -c "
      echo 'Running MinIO setup...';
      until (/usr/bin/mc alias set myminio http://minio:9000 admin password123); do echo 'Waiting for MinIO to start...'; sleep 3; done;
      /usr/bin/mc mb myminio/videos || true;
      /usr/bin/mc admin config set myminio notify_webhook:event_gw endpoint=\"http://event-gateway:8080/api/v1/webhooks/storage/minio\";
      /usr/bin/mc admin service restart myminio;
      sleep 5;
      until (/usr/bin/mc alias set myminio http://minio:9000 admin password123); do echo 'Waiting for MinIO to restart...'; sleep 3; done;
      /usr/bin/mc event add myminio/videos arn:minio:sqs::event_gw:webhook --event put;
      echo 'MinIO Webhook & Bucket setup completed!';
      "

volumes:
  mongodb_data:
  minio_data:
